[comm]
mode = "User"
icon_file = ""
det_threshold = 0.6
app_name_en = ""
app_name_zh-CN = ""
app_name_zh-TW = ""
app_name_fr = ""
app_name_ko = ""
app_name_es = ""
app_name_pt-BR = ""
app_name_ja = ""
title_name_en = ""
title_name_zh-CN = ""
title_name_zh-TW = ""
title_name_fr = ""
title_name_ko = ""
title_name_es = ""
title_name_pt-BR = ""
title_name_ja = ""
user_added_langs = []

[mindplus_options]
dataset_zip = ""
model_zip = ""

[user_options]
user_dir = ""
onnx_file = ""
